# Generated by Django 5.1.6 on 2025-06-23 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-start_time'], 'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rented_at',
        ),
        migrations.AddField(
            model_name='rental',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rental',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rental',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.equipment'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['start_time', 'end_time'], name='clients_ren_start_t_6d711a_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['equipment', 'start_time'], name='clients_ren_equipme_529c62_idx'),
        ),
    ]
