# Generated by Django 5.1.6 on 2025-06-23 21:33

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_rental_options_remove_rental_rented_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='end_time',
            field=models.DateTimeField(default=clients.models.default_end_time),
        ),
    ]
