# Generated by Django 5.1.6 on 2025-06-25 19:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_rental_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='clients.equipment'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['available', 'rented', 'maintenance'])), name='valid_equipment_status'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__gte', datetime.datetime(2025, 6, 24, 19, 7, 48, 352301, tzinfo=datetime.timezone.utc))), name='start_not_in_past'),
        ),
    ]
