# Generated by Django 5.1.6 on 2025-06-25 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_rental_client_alter_rental_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rental',
            name='start_not_in_past',
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__gte', datetime.datetime(2025, 6, 24, 19, 16, 46, 712512, tzinfo=datetime.timezone.utc))), name='start_not_in_past'),
        ),
    ]
