# Generated by Django 5.1.6 on 2025-06-25 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_rental_start_not_in_past_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rental',
            name='start_not_in_past',
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__gte', datetime.datetime(2025, 6, 24, 19, 17, 32, 937704, tzinfo=datetime.timezone.utc))), name='start_not_in_past'),
        ),
    ]
