# Generated by Django 5.1.6 on 2025-06-30 18:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_rental_start_not_in_past_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Начало обслуживания')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Окончание обслуживания')),
                ('description', models.TextField(blank=True, verbose_name='Описание работ')),
                ('performed_by', models.CharField(blank=True, max_length=100, verbose_name='Исполнитель')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='planned', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Обслуживание',
                'verbose_name_plural': 'Обслуживания',
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='rental',
            name='start_not_in_past',
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__gte', datetime.datetime(2025, 6, 29, 18, 24, 5, 725877, tzinfo=datetime.timezone.utc))), name='start_not_in_past'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='clients.equipment', verbose_name='Оборудование'),
        ),
    ]
